/*
Deployment script for master

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;

/*
Change the following paths to yours
*/
GO
:setvar DatabaseName "AndroShield"
:setvar DefaultFilePrefix "AndroShield"
:setvar DefaultDataPath "C:\Users\<userName>\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\<userName>\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating [dbo].[ApkInfo]...';


GO
CREATE TABLE [dbo].[ApkInfo] (
    [apkID]           INT           IDENTITY (1, 1) NOT NULL,
    [apkName]         VARCHAR (MAX) NULL,
    [minSDK]          VARCHAR (MAX) NULL,
    [targetSdk]       VARCHAR (MAX) NULL,
    [packageName]     VARCHAR (MAX) NULL,
    [versionCode]     VARCHAR (MAX) NULL,
    [versionName]     VARCHAR (MAX) NULL,
    [apkRiskLevel]    FLOAT (53)    NULL,
    [testOnlyFlag]    BIT           NULL,
    [debuggableFlag]  BIT           NULL,
    [backupFlag]      BIT           NULL,
    [allFlag]         BIT           NULL,
    [armeabiFlag]     BIT           NULL,
    [armeabi_v7aFlag] BIT           NULL,
    [arm64_V8aFlag]   BIT           NULL,
    [X86Flag]         BIT           NULL,
    [X86_64Flag]      BIT           NULL,
    [mipsFlag]        BIT           NULL,
    [mips64Flag]      BIT           NULL,
    CONSTRAINT [PkeyIDApkInfo] PRIMARY KEY CLUSTERED ([apkID] ASC)
);


GO
PRINT N'Creating [dbo].[apkInfo_Permission]...';


GO
CREATE TABLE [dbo].[apkInfo_Permission] (
    [apkInfoID]    INT NULL,
    [permissionID] INT NULL
);


GO
PRINT N'Creating [dbo].[launchableActivity]...';


GO
CREATE TABLE [dbo].[launchableActivity] (
    [launchableActivityID] INT           IDENTITY (1, 1) NOT NULL,
    [name]                 VARCHAR (MAX) NULL,
    [apkInfoID]            INT           NULL,
    CONSTRAINT [PkeyLaunchedActivity] PRIMARY KEY CLUSTERED ([launchableActivityID] ASC)
);


GO
PRINT N'Creating [dbo].[permission]...';


GO
CREATE TABLE [dbo].[permission] (
    [permissionID] INT           IDENTITY (1, 1) NOT NULL,
    [name]         VARCHAR (MAX) NULL,
    CONSTRAINT [Pkeypermission] PRIMARY KEY CLUSTERED ([permissionID] ASC)
);


GO
PRINT N'Creating [dbo].[report]...';


GO
CREATE TABLE [dbo].[report] (
    [reportID]            INT  IDENTITY (1, 1) NOT NULL,
    [reportDate]          DATE NULL,
    [staticallyAnalyzed]  BIT  NULL,
    [dynamicallyAnalyzed] BIT  NULL,
    [apkInfoID]           INT  NULL,
    [userAccountID]       INT  NULL,
    CONSTRAINT [PkeyReport] PRIMARY KEY CLUSTERED ([reportID] ASC)
);


GO
PRINT N'Creating [dbo].[report_Vulnerability]...';


GO
CREATE TABLE [dbo].[report_Vulnerability] (
    [reportID]        INT           NULL,
    [vulnerabilityID] INT           NULL,
    [extraInfo]       VARCHAR (MAX) NULL
);


GO
PRINT N'Creating [dbo].[userAccount]...';


GO
CREATE TABLE [dbo].[userAccount] (
    [userID]         INT           IDENTITY (1, 1) NOT NULL,
    [lastLoginDate]  DATE          NULL,
    [password]       VARCHAR (MAX) NULL,
    [email]          VARCHAR (MAX) NOT NULL,
    [firstName]      VARCHAR (MAX) NULL,
    [lastName]       VARCHAR (MAX) NULL,
    [facebookUserID] BIGINT        NULL,
    CONSTRAINT [PkeyuserAccount] PRIMARY KEY CLUSTERED ([userID] ASC)
);


GO
PRINT N'Creating [dbo].[vulnerability]...';


GO
CREATE TABLE [dbo].[vulnerability] (
    [vulnerabilityID] INT           IDENTITY (1, 1) NOT NULL,
    [category]        VARCHAR (MAX) NULL,
    [type]            VARCHAR (MAX) NULL,
    [severity]        FLOAT (53)    NULL,
    CONSTRAINT [Pkeyvulnerability] PRIMARY KEY CLUSTERED ([vulnerabilityID] ASC)
);


GO
PRINT N'Creating [dbo].[FK_apkInfo_PT]...';


GO
ALTER TABLE [dbo].[apkInfo_Permission] WITH NOCHECK
    ADD CONSTRAINT [FK_apkInfo_PT] FOREIGN KEY ([apkInfoID]) REFERENCES [dbo].[ApkInfo] ([apkID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_apkInfo_Permission]...';


GO
ALTER TABLE [dbo].[apkInfo_Permission] WITH NOCHECK
    ADD CONSTRAINT [FK_apkInfo_Permission] FOREIGN KEY ([permissionID]) REFERENCES [dbo].[permission] ([permissionID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_launchableActivity_APKINFO]...';


GO
ALTER TABLE [dbo].[launchableActivity] WITH NOCHECK
    ADD CONSTRAINT [FK_launchableActivity_APKINFO] FOREIGN KEY ([apkInfoID]) REFERENCES [dbo].[ApkInfo] ([apkID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_report_apkInfo]...';


GO
ALTER TABLE [dbo].[report] WITH NOCHECK
    ADD CONSTRAINT [FK_report_apkInfo] FOREIGN KEY ([apkInfoID]) REFERENCES [dbo].[ApkInfo] ([apkID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_report_userAccount]...';


GO
ALTER TABLE [dbo].[report] WITH NOCHECK
    ADD CONSTRAINT [FK_report_userAccount] FOREIGN KEY ([userAccountID]) REFERENCES [dbo].[userAccount] ([userID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_reportVuln]...';


GO
ALTER TABLE [dbo].[report_Vulnerability] WITH NOCHECK
    ADD CONSTRAINT [FK_reportVuln] FOREIGN KEY ([reportID]) REFERENCES [dbo].[report] ([reportID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_reportVulnerability]...';


GO
ALTER TABLE [dbo].[report_Vulnerability] WITH NOCHECK
    ADD CONSTRAINT [FK_reportVulnerability] FOREIGN KEY ([vulnerabilityID]) REFERENCES [dbo].[vulnerability] ([vulnerabilityID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[apkInfo_Permission] WITH CHECK CHECK CONSTRAINT [FK_apkInfo_PT];

ALTER TABLE [dbo].[apkInfo_Permission] WITH CHECK CHECK CONSTRAINT [FK_apkInfo_Permission];

ALTER TABLE [dbo].[launchableActivity] WITH CHECK CHECK CONSTRAINT [FK_launchableActivity_APKINFO];

ALTER TABLE [dbo].[report] WITH CHECK CHECK CONSTRAINT [FK_report_apkInfo];

ALTER TABLE [dbo].[report] WITH CHECK CHECK CONSTRAINT [FK_report_userAccount];

ALTER TABLE [dbo].[report_Vulnerability] WITH CHECK CHECK CONSTRAINT [FK_reportVuln];

ALTER TABLE [dbo].[report_Vulnerability] WITH CHECK CHECK CONSTRAINT [FK_reportVulnerability];


GO
PRINT N'Update complete.';


GO
